Repository urbandataanalytics/SwissKnife, pull requests merged in 2020-04, with the labels that each got.

#2 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#1 Create code of conduct document
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#3 Feature/get bucket path
  README.md
  SwissKnife/info/__init__.py
  tests/info/__init__.py
  tests/info/test_BUCKET_PATH.py
  tests/info/test_CURRENT_ENVIRONMENT.py
  tests/info/test_ExecutionEnvironment.py
Labels: documentation, enhancement

#4 Divided BUCKET_PATH variable into two different ones.
  CHANGELOG.md
  SwissKnife/info/BucketPath.py
  SwissKnife/info/__init__.py
  setup.py
  tests/info/test_BUCKET_PATH.py
Labels: enhancement

#5 Feature/gcloud storage functions
  CHANGELOG.md
  Makefile
  SwissKnife/gcloud/GCloudStorage.py
  setup.py
  tests/gcloud/test_GCloudStorage.py
  tests/info/__init__.py
  tests/info/test_BUCKET_PATH.py
  tests/info/test_CURRENT_ENVIRONMENT.py
  tests/test_utils.py
Labels: enhancement

#6 Hotfix/typo in variable
  CHANGELOG.md
  SwissKnife/gcloud/GCloudStorage.py
  SwissKnife/gcloud/GCloudStreaming.py
  setup.py
  tests/gcloud/test_GCloudStorage.py
Labels: bug
