Repository urbandataanalytics/SwissKnife, pull requests merged in 2020-05, with the labels that each got.

#9 Make ExecutionEnvironment JSON serializable
  CHANGELOG.md
  SwissKnife/info/ExecutionEnvironment.py
  setup.py
  tests/info/test_CURRENT_ENVIRONMENT.py
Labels: bug

#7 Incubating AvroTransformer in SwissKnife
  .gitignore
  CHANGELOG.md
  SwissKnife/avro/AvroTransformer.py
  SwissKnife/avro/types.py
  tests/avro/test_AvroTransformer.py
Labels: enhancement

#10 Adding calendar function that returns the week number given a timestamp
  CHANGELOG.md
  SwissKnife/avro/AvroTransformer.py
  SwissKnife/calendar/WeekUtils.py
  tests/calendar/__init__.py
  tests/calendar/test_WeekUtils.py
Labels: enhancement

#12 Add bucket prefix path (resolves #11)
  CHANGELOG.md
  SwissKnife/gcloud/GCloudStorage.py
  tests/gcloud/test_GCloudStorage.py
Labels: bug, enhancement
